# Generated by Django 6.0.2 on 2026-03-04 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="部门名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("student", "学生/成员"), ("teacher", "老师/导员")],
                        default="student",
                        max_length=20,
                        verbose_name="身份类型",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="学号/工号"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=11, verbose_name="电话"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="是否管理员"),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        to="core.department",
                        verbose_name="所属部门（可多选）",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "成员",
                "verbose_name_plural": "成员",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="考勤日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "正常出勤"),
                            ("late", "迟到"),
                            ("absent", "缺席"),
                            ("leave", "请假"),
                        ],
                        default="present",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.member",
                        verbose_name="成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
                "unique_together": {("student", "date")},
            },
        ),
    ]
