<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-03-04 12:06
=======
# Generated by Django 6.0.2 on 2026-03-13 08:34
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Student",
=======
            name="Department",
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
<<<<<<< HEAD
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("class_name", models.CharField(max_length=50, verbose_name="班级")),
=======
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="部门名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("student", "学生/成员"), ("teacher", "老师/导员")],
                        default="student",
                        max_length=20,
                        verbose_name="身份类型",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="学号/工号"
                    ),
                ),
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                (
                    "phone",
                    models.CharField(blank=True, max_length=11, verbose_name="电话"),
                ),
                (
<<<<<<< HEAD
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_id",
                    models.CharField(max_length=20, unique=True, verbose_name="工号"),
                ),
                ("department", models.CharField(max_length=50, verbose_name="院系")),
                (
                    "title",
                    models.CharField(blank=True, max_length=20, verbose_name="职称"),
                ),
=======
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="是否管理员"),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        to="core.department",
                        verbose_name="所属部门（可多选）",
                    ),
                ),
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
<<<<<<< HEAD
                        related_name="teacher_profile",
=======
                        related_name="member_profile",
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
<<<<<<< HEAD
=======
            options={
                "verbose_name": "成员",
                "verbose_name_plural": "成员",
            },
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="考勤日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
<<<<<<< HEAD
                            ("present", "正常"),
                            ("late", "迟到"),
                            ("absent", "旷课"),
=======
                            ("present", "正常出勤"),
                            ("late", "迟到"),
                            ("absent", "缺席"),
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                            ("leave", "请假"),
                        ],
                        default="present",
                        max_length=10,
<<<<<<< HEAD
                        verbose_name="考勤状态",
=======
                        verbose_name="状态",
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
<<<<<<< HEAD
                        to="core.student",
                        verbose_name="学生",
=======
                        to="core.member",
                        verbose_name="成员",
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                    ),
                ),
            ],
            options={
<<<<<<< HEAD
=======
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
>>>>>>> 03f2d59 (feat: 优化界面风格，实现多部门选择及Tom Select交互)
                "unique_together": {("student", "date")},
            },
        ),
    ]
