# Generated by Django 6.0.3 on 2026-03-12 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会议名称')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='开会地点')),
                ('start_time', models.DateTimeField(verbose_name='预计开始时间')),
                ('end_time', models.DateTimeField(verbose_name='预计结束时间')),
                ('enable_checkin', models.BooleanField(default=True, verbose_name='开启签到')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='与会成员')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.meeting', verbose_name='会议')),
            ],
            options={
                'unique_together': {('user', 'meeting')},
            },
        ),
        migrations.DeleteModel(
            name='PunchRecord',
        ),
    ]
